apiVersion: v1
kind: ConfigMap
metadata:
  name: <CONFIG_MAP_NAME>
  namespace: default
data:
  ENV: <ENV>
  BOT_AND_SETUP_SERVICE_URL: <BOT_AND_SETUP_SERVICE_URL>
  BOT_API_URL: <BOT_API_URL>
  BOT_X_API_KEY: <BOT_X_API_KEY>
  DATABASE_URL: <DATABASE_URL>
  EXCHANGE_SERVICE_URL: <EXCHANGE_SERVICE_URL>
  FIREBASE_API_KEY: <FIREBASE_API_KEY>
  MAILGUN_DOMAIN: <MAILGUN_DOMAIN>
  MAILGUN_KEY: <MAILGUN_KEY>
  MAILGUN_URL: <MAILGUN_URL>
  NETWORK_CHAIN_ID: <NETWORK_CHAIN_ID>
  NETWORK_JSON_RPC: <NETWORK_JSON_RPC>
  RABBITMQ_URI: <RABBITMQ_URI>
  REDIS_URL: <REDIS_URL>
  TELEGRAM_BOT_API: <TELEGRAM_BOT_API>
  WEB_APP_URL: <WEB_APP_URL>
  FIREBASE_SERVICE_ACCOUNT: |-
    <FIREBASE_SERVICE_ACCOUNT>